### ISSUE TITLE
Configure wekan service to use https

### ISSUE THREAD

**Issue by khba** [wekan/wekan-mongodb#1]
Hello,
After a satisfying installation of Wekan with your docker-compose.yml file, I'm trying to make it available in https to secure passwords on the network. I change the docker-compose.yml file like this: 

			version: '2'
			services:
			  wekandb:
				image: mongo:3.2.12
				container_name: wekan-db
				restart: always
				user: mongodb
				command: mongod --smallfiles --oplogSize 128
				networks:
				  - wekan-tier
				expose:
				  - 27017
				volumes:
				  - wekan-db:/data/db
				  - wekan-db-dump:/dump

			  wekan:
				image: mquandalle/wekan:latest
				container_name: wekan-app
				restart: always
				networks:
				  - wekan-tier
				ports:
				  - 443:443
				environment:
				  - MONGO_URL=mongodb://wekandb:27017/wekan
				  - ROOT_URL=https://127.0.0.1
				depends_on:
				  - wekandb

			volumes:
			  wekan-db:
				driver: local
			  wekan-db-dump:
				driver: local

			networks:
			  wekan-tier:
				driver: bridge

But despite asking it to listen to 443 port, wekan is still available only in 80 and I can see this in running processes: 

root     27097 26966  0 10:01 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip X.X.X.X -container-port 80

Why is that, any idea on how to switch it to HTTPS? I tried the following things: 
-Found no SSL/TLS options in docker-compose documentation;
-Couldn't find how or in which file of the world configure the docker-proxy to use the 443  instead of 80 ;
-Tried to conf an https_proxy  like this: https://docs.docker.com/engine/admin/systemd/#start-manually ==> changes nothing ;
-Installed a local apache service , configured it in https, and tried to redirect all the web traffic through it, didn't find how to tell to dockerd to do so.

Any help ?

**Comment by xet7** [comment]
@khba 

Currently we have configs only for Caddy and Nginx, not Apache yet. Anyway, you need to enable websockets.
https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

Wekan ROOT_URL needs to be real address to Wekan:
```
ROOT_URL=https://example.com/wekan
```

On UFW or other firewall you need to allow 80 and 443.
Webserver 443 proxies to localhost port of Docker you choose, for example 8080.

Example of mapping port 80 inside Docker to port 8080 outside Docker, similar can be used in Docker Compose file:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
```
docker run -d --restart=always --name wekan-db mongo:3.2.12

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=https://example.com/wekan" -p 8080:80 mquandalle/wekan:latest
```

You can also use Docker Compose to for multiple containers, like Caddy/Nginx, like is combined in PostgreSQL example:
https://github.com/wekan/wekan-postgresql

You can use Docker Volumes feature to keep and mount persistent data on some directory.

If you'd like to have some WEB UI for Docker, try http://portainer.io

**Comment by khba** [comment]
Thanks @xet7 , 

For posterity here is what finally did:
I finally made it by removing apache and installing nginx to use it as proxy.  I took this as example https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config and changed my conf file like this:


# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;


	server_tokens off; # for security-by-obscurity: stop displaying nginx version

	# this section is needed to proxy web-socket connections
	map $http_upgrade $connection_upgrade {
		default upgrade;
		''      close;
	}

	# HTTP
	server {
		listen MY-HOST-IP:80;

		server_name docker-hbs1; # the domain on which we want to host the application. Since we set "default_server" previously, nginx will answer all hosts anyway.

		# redirect non-SSL to SSL
		location / {
			rewrite     ^ https://MY-HOST-IP;
		}
	}

	# HTTPS server

	server {
		listen MY-HOST-IP:443 ssl;
		server_name docker-hbs1; # this domain must match Common Name (CN) in the SSL certificate

		ssl_certificate /etc/nginx/ssl/nginx-server.crt; # full path to SSL certificate and CA certificate concatenated together
		ssl_certificate_key /etc/nginx/ssl/nginx-server.deprotected.key; # full path to SSL key

		# performance enhancement for SSL
		ssl_stapling on;
		ssl_session_cache shared:SSL:10m;
		ssl_session_timeout 5m;

		# safety enhancement to SSL: make sure we actually use a safe cipher
		ssl_prefer_server_ciphers on;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK';

		# config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
		# to avoid ssl stripping https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
		add_header Strict-Transport-Security "max-age=31536000;";

		# If your application is not compatible with IE <= 10, this will redirect visitors to a page advising a browser update
		# This works because IE 11 does not present itself as MSIE anymore
		if ($http_user_agent ~ "MSIE" ) {
			return 303 https://browser-update.org/update.html;
		}

		# pass all requests to Meteor
		location / {
			proxy_pass http://127.0.0.1:8081;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade; # allow websockets
			proxy_set_header Connection $connection_upgrade;
			proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP

			# this setting allows the browser to cache the application in a way compatible with Meteor
			# on every applicaiton update the name of CSS and JS file is different, so they can be cache infinitely (here: 30 days)
			# the root path (/) MUST NOT be cached
			if ($uri != '/wekan') {
				expires 30d;
			}
		}
	}
}


My final docker-compose.yml

version: '2'

services:

  wekandb:
    image: mongo:3.2.12
    container_name: wekan-db
    restart: always
    user: mongodb
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: mquandalle/wekan:latest
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 8081:80
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://MY-HOST-IP
      - MAIL_URL=smtp://MY-HOST-IP:25/
      - MAIL_FROM=wekan@mydomain.fr
    depends_on:
      - wekandb

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge

The problems I encountered with given nginx file are :
*The redirection 80=>443 wasn't working with this 
rewrite     ^ https://$server_name$request_uri? permanent;
Even after replacing $server_name with my server ip, so I finally replaced it with a simple redirect that worked.
*Things also didn't work with /wekan. I had to remove it everywhere. Maybe it was me missing some detail but these two conf files are what finally worked, feel free to tell me if some things are against best practices.

Last but not least, if you have selinux enabled, you'll have to do this for the proxy to work:
setsebool -P httpd_can_network_connect on
