### ISSUE TITLE
failed to connect to server [wekandb:27017] on first connect

### ISSUE THREAD

**Issue by haiyin27** [wekan/wekan-mongodb#14]
follow the install steps:
at docker-compose up,get the error
wekan-app  | 
wekan-app  | /build/programs/server/node_modules/fibers/future.js:313
wekan-app  | 						throw(ex);
wekan-app  | 						^

wekan-app  | MongoError: failed to connect to server [wekandb:27017] on first connect [MongoError: getaddrinfo ENOTFOUND wekandb wekandb:27017]
wekan-app  |     at Pool.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
wekan-app  |     at emitOne (events.js:116:13)
wekan-app  |     at Pool.emit (events.js:211:7)
wekan-app  |     at Connection.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
wekan-app  |     at Object.onceWrapper (events.js:317:30)
wekan-app  |     at emitTwo (events.js:126:13)
wekan-app  |     at Connection.emit (events.js:214:7)
wekan-app  |     at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
wekan-app  |     at Object.onceWrapper (events.js:315:30)
wekan-app  |     at emitOne (events.js:116:13)

**Comment by Teutone** [comment]
Did you try out entering your IP - I was struggling with a similar issue today and it's all about DNS resolving

**Comment by BobCashStory** [comment]
same for me if i use admin user to the db

**Comment by xet7** [comment]
Sorry, I fixed docker-compose.yml, please download it and try again.
