### ISSUE TITLE
Suggested upgrade path from 0.77

### ISSUE THREAD

**Issue by craig-silva** [wekan/wekan-mongodb#15]
I've been pleased/happy with v0.77 wekan-mongodb container.

But thought I'ld try an upgrade - and went stright to latest - failed.

So I probably missed the odd schema change or such.

Any suggestions on a stepped approach?

BTW - thanks for the docs on backup and restore - saved my bacon :->

**Comment by xet7** [comment]
@craig-silva 

I created wiki page for manual steps.
https://github.com/wekan/wekan/wiki/Migrating-from-old-Wekan-manually
