### ISSUE TITLE
hello, when  running the application,  I find a problem:/build/programs/server/node_modules/fibers/future.js:280 threw(ex)

### ISSUE THREAD

**Issue by chentyler** [wekan/wekan-mongodb#16]
Presence started serverId=m82bcFrRxPpuSMKN9
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
/build/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

TypeError: Cannot read property 'constructor' of undefined
    at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
    at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
    at packages/meteorhacks_meteorx.js:175:1
    at packages/meteorhacks_meteorx.js:200:4
    at packages/meteorhacks_meteorx.js:208:3
    at /build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:220:19
    at /build/programs/server/boot.js:471:5
    at Function.run (/build/programs/server/profile.js:510:12)
    at /build/programs/server/boot.js:470:11

----------------------------------------------------------------
**The above text is the problem I encountered in my operation.**  please help me .thanks！

**Comment by xet7** [comment]
Please try newest wekan.
