### ISSUE TITLE
ERROR: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by NotRodeo** [wekan/wekan-mongodb#21]
Error shows up when running command  `docker-compose up -d --build`

**Comment by xet7** [comment]
What docker image you are using? Docker Hub? That looks like Docker Hub having server problems, not Wekan.

Try this:
```
image: quay.io/wekan/wekan
```

**Comment by xet7** [comment]
Actually, it seems you are trying to build from source. 

You need edit docker-compose.yml to uncomment these lines:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L132-L142

And then run:
```
docker-compose up -d --build
```

**Comment by NotRodeo** [comment]
Sorry to bother you , I just uncomment L132-142 like you said , and ran `docker-compose up -d --build`, and shows  

> ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Am I having an internet issue?

**Comment by xet7** [comment]
It looks like docker hub has maintenance in progress. Try again later.
https://status.docker.com/
