### ISSUE TITLE
how to update wekan version

### ISSUE THREAD

**Issue by biji** [wekan/wekan-mongodb#3]
How to update wekan version to latest (0.46) without losing data (existing containers)?
Kindly please add to readme :smile: 

Thanks

**Comment by biji** [comment]
sorry , there's already in wekan wiki

https://github.com/wekan/wekan/wiki/Install-and-Update#updating-docker

**Comment by xet7** [comment]
@biji 

Yes, and on wiki menu Features / Backups this:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
