### ISSUE TITLE
Exception while invoking method 'ATCreateUserServer' Error: self signed certificate

### ISSUE THREAD

**Issue by Paw2Pom** [wekan/wekan-mongodb#5]
I have created a docker-compose file and it can startup no problem. However when I go to the login page and tried to register a new user (i.e. insert username, email and password), I have got the following errors on the page:

Internal server error

And I have got the following error log from the docker-compose:

wekan-app     | Exception while invoking method 'ATCreateUserServer' Error: self signed certificate
wekan-app     |     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
wekan-app     |     at emitNone (events.js:106:13)
wekan-app     |     at TLSSocket.emit (events.js:208:7)
wekan-app     |     at TLSSocket._finishInit (_tls_wrap.js:637:8)
wekan-app     |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
wekan-postfix | Feb 13 15:55:47 wekan-postfix postfix/smtpd[203]: connect from wekan-app.02dcwekan_wekan-tier[172.18.0.4]
wekan-postfix | Feb 13 15:55:47 wekan-postfix postfix/smtpd[203]: lost connection after STARTTLS from wekan-app.02dcwekan_wekan-tier[172.18.0.4]
wekan-postfix | Feb 13 15:55:47 wekan-postfix postfix/smtpd[203]: disconnect from wekan-app.02dcwekan_wekan-tier[172.18.0.4]

**Comment by Paw2Pom** [comment]
My docker-compose file is as follow:


version: '2'

services:

  wekandb:
    # All Wekan data is stored in MongoDB. For backup and restore, see:
    #   https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
    image: mongo:3.2.18
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /srv/wekan-db:/data/db
      - /srv/wekan-db-dump:/dump

  wekan:
    # Wekan container only has Node.js and related code,
    # there is no data stored here.
    #
    # Docker Hub, updates more slowly
    #image: wekanteam/wekan:latest
    #
    # Quay, updates faster
    image: quay.io/wekan/wekan
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    #---------------------------------------------------------------
    # For running Wekan in different port like 3000, use: 3000:80
    ports:
      - 8081:80
    #---------------------------------------------------------------
    # Change ROOT_URL to your real Wekan URL, for example:
    #   http://example.com
    #   http://example.com/wekan
    #   http://192.168.1.100
    #---------------------------------------------------------------
    # Email settings are required in both MAIL_URL and Admin Panel,
    #   see https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
    #   For SSL in email, change smtp:// to smtps://
    #---------------------------------------------------------------
    # Not needed on Docker, but if you had installed from source,
    #   you could also have setup Wekan Node.js port at localhost
    #   with setting: PORT=3000
    #   and have Nginx proxy to port 3000, see Wekan wiki.
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://192.168.1.121:8081
      # - MAIL_URL=smtp://user:pass@mailserver.example.com:25/
      - MAIL_URL=smtp://wekan:wekan@mailserver:25
      - MAIL_FROM='Example Wekan Support <support@example.com>'
    depends_on:
      - wekandb

  mailserver:
    image: marvambass/versatile-postfix
    container_name: wekan-postfix
    hostname: wekan-postfix
    ports:
      - 25:25
    networks:
      - wekan-tier
    environment:
      - ALIASES=postmaster:root;hostmaster:root;webmaster:root
    volumes:
      - /srv/wekan/postfix/maildirs:/var/mail
      - /srv/wekan/postfix/dkim:/etc/postfix/dkim/
    command: example.com wekan:wekan

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge

**Comment by xet7** [comment]
Your mailserver uses unsigned SSL sertificate. That requires at least that in mail url:
MAIL_URL=smtp://wekan:wekan@mailserver:25

You change smtp => smtps , and to correct port - not 25 that is not encrypted
For more info see https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Also invitation emails can not be resent yet https://github.com/wekan/wekan/issues/1320

Anyway working email is not required for normal usage of Wekan. When registering new user at /sign-up , you get error because email is not configured, but account is created anyway and you can login at url /sign-in .

Those email bugs will be fixed sometime this year.

**Comment by Paw2Pom** [comment]
Awesome, it works now by commenting out the mail_url! Thanks!
