### ISSUE TITLE
Server was restarted, data loss? (MongoError: failed to connect to server [wekandb:27017] on first connect)

### ISSUE THREAD

**Issue by CodeBrauer** [wekan/wekan-mongodb#8]
So, the server was restarted by an admin.

I don't know why, docker didn't startup the wekan-containers on reboot.

I started them manually:

1. I noticed `wekan-db` had no mounted/attached volumes so it created some new..
2. `wekan-app` had the following error message:

```
/build/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [wekandb:27017] on first connect
    at Object.Future.wait (/build/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
[...]
```

So I just recreated the container with the correct volume mounts (`/var/lib/docker/volumes/wekan_wekan-db` & `/var/lib/docker/volumes/wekan_wekan-db-dump`)

Before starting I checked the folders:
- `wekan_wekan-db-dump` is empty
- `wekan_wekan-db` contains lots of '.wt' files and is about 450MB big. **I hope this is my data!**

So I started the containers and after some time wekan was reachable but the mongodb is empty.

```
# checking docker

root@plesk:~# docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                            NAMES
323080c2075c        mongo:3.2.18                    "docker-entrypoint..."   9 minutes ago       Up 9 minutes        0.0.0.0:32769->27017/tcp                         wekan-db
c04aabc12d3c        wekanteam/wekan:latest          "node /build/main.js"    21 minutes ago      Up 19 seconds       0.0.0.0:4000->80/tcp                             wekan-app
f639ae8a30f0        portainer/portainer             "/portainer"             About an hour ago   Up 16 minutes       0.0.0.0:9000->9000/tcp                           portainer
ee62fc1c9f7b        softinstigate/restheart:3.2.0   "./entrypoint.sh e..."   2 months ago        Up 9 minutes        0.0.0.0:4043->4443/tcp, 0.0.0.0:4040->8080/tcp   restheart
root@plesk:~# docker inspect -f "{{ .Mounts }}" 323080c2075c
[{bind  /var/lib/docker/volumes/wekan_wekan-db /data/db   true } {bind  /var/lib/docker/volumes/wekan_wekan-db-dump /dump   true } {volume a0616dc8c91d25345343b344d9bbe30574a732bd28dbc917ce04a9db16f3e239 /var/lib/docker/volumes/a0616dc8c91d25345343b344d9bbe30574a732bd28dbc917ce04a9db16f3e239/_data /data/configdb local  true }]

# checking mongo

root@plesk:~# docker exec -it wekan-db bash
root@62ea1a6b2081:/# mongo
MongoDB shell version: 3.2.18
connecting to: test
Server has startup warnings:
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten]
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten]
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-03-15T09:15:38.429+0000 I CONTROL  [initandlisten]
> db.users.find()
```

So what could go wrong? How can I restore my data?

**Comment by xet7** [comment]
@CodeBrauer 

1) I recommend you backup your /var/lib/docker/ directory, because somewhere there in those old containers could be your data. It's possible that you have started new MongoDB container with empty data, and it's in another new directory. You see dates of files with `ls -lah`.

2) Those 450MB of data could be the correct ones, but you need to stop Wekan and MongoDB before you copy those files back, so they don't get corrupted.

Also see:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

**Comment by xet7** [comment]
@CodeBrauer 

For backup of /var/lib/docker, use command to keep file permissions:
https://askubuntu.com/questions/225865/copy-files-without-losing-file-folder-permissions

**Comment by xet7** [comment]
@CodeBrauer 

I think you also need to stop docker first:
```
sudo systemctl stop docker
```
or alternatively:
```
sudo service docker stop
```

**Comment by xet7** [comment]
@CodeBrauer 

```
docker exec -it wekan-db bash

mongo
```
Show databases:
```
show dbs
```

If there is database name wekan or admin, and use it:
```
use wekan                ( or: use admin)
```

Show collections of that database:
```
show collections
```

Find users:
```
db.users.find();
```

**Comment by xet7** [comment]
It is defined in docker-compose.yml file what database is used, at right end of line, is it wekan or admin:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L85

**Comment by CodeBrauer** [comment]
I know it was *wekan* because I already used it before with RESTHeart...

```
> show dbs
local  0.000GB
> use wekan
switched to db wekan
> show collections
> db.users.find();
>
```

**Comment by xet7** [comment]
@CodeBrauer 

If you have backup of those files, you can try to fix MongoDB database:
https://docs.mongodb.com/manual/reference/command/repairDatabase/

**Comment by xet7** [comment]
Those commands currently show that only local database is visible, not any others.

**Comment by CodeBrauer** [comment]
Sadly it seems the database is still empty:

```
root@62ea1a6b2081:/# mongo
MongoDB shell version: 3.2.18
connecting to: test
Server has startup warnings:
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten]
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten]
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-03-15T10:15:52.827+0000 I CONTROL  [initandlisten]
> db.repairDatabase();
{ "ok" : 1 }
> show dbs
local  0.000GB
> use wekan
switched to db wekan
> show collections
>
```

**Comment by xet7** [comment]
- Do you have earlier backup that you can restore?
- It could be possible to look at those files with hex editor, to see what is in those files

I'm trying to think other possible ways to continue.

**Comment by CodeBrauer** [comment]
I have to find a simple hex viewer that can handle more than 200mb on macOS - but here is the `_data` files list:

I have high hopes that `collection-0-2713973085537274806.wt` could contain my data.

![bildschirmfoto 2018-03-15 um 11 59 56](https://user-images.githubusercontent.com/2059754/37459555-c45c5854-2848-11e8-81bf-419a64845e38.png)

**Comment by CodeBrauer** [comment]
The file can't be read without further processing:

![bildschirmfoto 2018-03-15 um 12 04 01](https://user-images.githubusercontent.com/2059754/37459673-230e4330-2849-11e8-9099-ba5cdabf123c.png)

**Comment by xet7** [comment]
You could google search more about mongodb file format, repairing, etc.

**Comment by xet7** [comment]
If you find out how to get data from that file, it would be helpful that you add info to this issue as comment too, because I have not had time to look at MongoDB file recovery yet.

**Comment by CodeBrauer** [comment]
Already looking into restoring the file. Think this issue is not really related to wekan/the stack itself.

For now it seems that mongod has overwritten my old database with keeping the old WiredTiger files in place

Of cause I will keep this issue updated. Thank you for your efforts! :)

**Comment by CodeBrauer** [comment]
I'm so mad I haven't made a backup of this directory. Anything else is well saved - except this. 😅

**Comment by CodeBrauer** [comment]
Didn't found any further information about this - Let's hope database administrators on stackexchange can help: https://dba.stackexchange.com/questions/200344/restore-corrupt-mongo-db-from-wiredtiger-files

**Comment by xet7** [comment]
I added links to these backup related issues to here:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
